name: corr
dependencies:
  - python=3.7
  - nose=1.3.7
  - flask=1.0.2
  - requests=2.21.0
  - cssselect=1.0.3
  - docopt=0.6
  - gunicorn=19.9.0
  - pip:
    - pymongo==3.7.2
    - boto3==1.9.80
    - werkzeug==0.14.1
    - mongoengine==0.16.3
    - flask-mongoengine==0.9.5
    - flask-testing==0.7.1
    - click==7.0
    - flask-restful==0.3.7
    - flask-api==1.1
    - flask-stormpath==0.4.8
    - hurry.filesize==0.9
    - flask-restful-swagger==0.20.1
    - simplejson==3.16.0
    - clamd==1.0.2
    - gevent==1.4.0
    - greenlet==0.4.15
